// Package cmdlist holds the shared command catalog (name -> help text).
// It has zero platform dependencies on purpose: the controller HTTP layer
// and mobile builds import this instead of internal/commands, whose engine
// pulls in Windows-only packages (registry, user32).
package cmdlist

// Known mirrors Controller.Dev KnownCommands for autocomplete/help.
var Known = map[string]string{
	"help":                    "Show help - help [command]",
	"list-commands":           "List all commands",
	"get-system-info":         "Get system info",
	"get-cpu-info":            "Get CPU info",
	"get-cpu-usage":           "Get CPU usage %",
	"get-memory-usage":        "Get memory usage",
	"get-disk-usage":          "Get disk usage - get-disk-usage [path]",
	"get-disk-health":         "Get disk health",
	"get-gpu-info":            "Get GPU info",
	"get-bios-info":           "Get BIOS info",
	"get-bios-version":        "Get BIOS version",
	"get-motherboard-info":    "Get motherboard info",
	"get-ram-slots":           "Get RAM slots",
	"get-battery":             "Get battery info",
	"get-battery-health":      "Get battery health",
	"get-display-info":        "Get display info",
	"get-display-resolution":  "Get display resolution",
	"get-monitors":            "Get monitors list",
	"get-screen-size":         "Get screen size",
	"get-system-load":         "Get system load",
	"get-uptime":              "Get uptime",
	"get-time":                "Get current time",
	"get-timezone":            "Get timezone",
	"get-startup-programs":    "Get startup programs",
	"get-services":            "Get services",
	"get-processes":           "Get processes",
	"get-scheduled-tasks":     "Get scheduled tasks",
	"get-installed-programs":  "Get installed programs",
	"get-user-groups":         "Get user groups",
	"get-user-rights":         "Get user rights",
	"get-hostname":            "Get hostname",
	"get-username":            "Get username",
	"get-os-version":          "Get OS version",
	"get-status":              "Get agent status",
	"get-version":             "Get agent version",
	"version":                 "Show local app version",
	"set-agent-token":         "Store agent registration token - set-agent-token <token>",
	"list-directory":          "List directory - list-directory <path>",
	"read-file":               "Read file - read-file <path>",
	"write-file":              "Write file - write-file <path>|<content> (separator |)",
	"append-file":             "Append to file - append-file <path>|<content>",
	"prepend-file":            "Prepend to file",
	"delete-item":             "Delete file or dir - delete-item <path>",
	"create-directory":        "Create directory - create-directory <path>",
	"copy-item":               "Copy file/dir - copy-item <src>|<dst>",
	"move-item":               "Move file/dir - move-item <src>|<dst>",
	"rename-item":             "Rename - rename-item <path>|<newName>",
	"get-file-info":           "Get file info - get-file-info <path>",
	"get-file-hash":           "Get file hash - get-file-hash <path>",
	"get-file-version":        "Get file version",
	"get-directory-size":      "Get directory size - get-directory-size <path>",
	"search-files":            "Search files - search-files <path>|<pattern>",
	"compress-item":           "Compress - compress-item <src>|<dst.zip>",
	"expand-item":             "Expand zip - expand-item <src>|<dst>",
	"compare-files":           "Compare files",
	"edit-line":               "Edit line in file",
	"delete-line":             "Delete line",
	"insert-line":             "Insert line",
	"backup-file":             "Backup file",
	"run-command":             "Run command - run-command <cmd>",
	"run-powershell":          "Run PowerShell - run-powershell <script>",
	"run-script":              "Run script",
	"launch-app":              "Launch app - launch-app <path>",
	"open-url":                "Open URL - open-url <url>",
	"wsl-execute":             "WSL execute",
	"get-ip-address":          "Get IP addresses",
	"get-network-info":        "Get network info",
	"get-network-connections": "Get network connections",
	"get-wifi-networks":       "Get WiFi networks",
	"get-wifi-profiles":       "Get WiFi profiles",
	"get-wifi-password":       "Get WiFi password",
	"get-public-ip":           "Get public IP",
	"resolve-dns":             "Resolve DNS - resolve-dns <host>",
	"trace-route":             "Trace route",
	"test-connection":         "Test connection - test-connection <host>",
	"check-port":              "Check port - check-port <host> <port>",
	"get-open-ports":          "Get open ports",
	"flush-dns":               "Flush DNS",
	"get-arp-cache":           "Get ARP cache",
	"get-route-table":         "Get route table",
	"mouse-move":              "Move mouse - mouse-move <x>,<y>",
	"mouse-click":             "Mouse click",
	"mouse-doubleclick":       "Mouse double click",
	"mouse-button":            "Mouse button - mouse-button <left|right|middle> <down|up>",
	"mouse-scroll":            "Mouse scroll - mouse-scroll <delta>",
	"get-position":            "Get mouse position",
	"send-text":               "Send text - send-text <text>",
	"key-press":               "Key press - key-press <key>",
	"clipboard-get":           "Get clipboard",
	"clipboard-set":           "Set clipboard - clipboard-set <text>",
	"get-active-window":       "Get active window",
	"lock-screen":             "Lock screen",
	"minimize-all-windows":    "Minimize all windows",
	"set-wallpaper":           "Set wallpaper - set-wallpaper <path>",
	"set-brightness":          "Set brightness 0-100",
	"set-volume":              "Set volume 0-100",
	"get-audio-devices":       "Get audio devices",
	"list-audio-endpoints":    "Audio endpoints as JSON (device pickers)",
	"get-audio-level":         "Audio level meter (JSON master/mic peaks)",
	"get-audio-volume":        "Get audio volume",
	"set-audio-volume":        "Set audio volume",
	"set-mic-mute":            "Set mic mute on/off",
	"set-default-audio-device": "Set default audio device - set-default-audio-device <id|name>",
	"start-audio-stream":       "Stream remote audio to controller - start-audio-stream [desktop|mic]",
	"stop-audio-stream":        "Stop remote audio streaming",
	"send-notification":        "Show window on remote PC - send-notification <seconds|sticky> <text>",
	"speak":                    "Speak text on remote PC - speak <text>",
	"speak-stop":               "Stop remote speech",
	"keep-awake":               "Block sleep/lock on remote PC - keep-awake [on|off|status]",
	"get-session-state":        "Locked/RDP state of remote session",
	"get-foreground-window":    "Focused window on remote PC (where keys land)",
	"get-agent-log":            "Pull remote agent log - get-agent-log [lines]",
	"get-agent-debug-log":      "Pull remote verbose log - get-agent-debug-log [lines]",
	"kill-agent":               "Terminate the agent process (stays dead until logon/manual start)",
	"mouse-click-at":           "Move+click atomically - mouse-click-at <x>,<y>",
	"mouse-doubleclick-at":     "Move+doubleclick atomically - mouse-doubleclick-at <x>,<y>",
	"force-update":             "Push bundled agent update to selected agent (controller-side)",
	"reg-read":                "Reg read - reg-read <path>",
	"reg-write":               "Reg write - reg-write <path>|<value>",
	"reg-delete":              "Reg delete - reg-delete <path>",
	"reg-enum-keys":           "Reg enum keys - reg-enum-keys <path>",
	"reg-enum-values":         "Reg enum values - reg-enum-values <path>",
	"reg-export":              "Reg export",
	"get-firewall-status":     "Get firewall status",
	"get-defender-status":     "Get defender status",
	"get-installed-updates":   "Get installed updates",
	"list-users":              "List users",
	"list-groups":             "List groups",
	"get-dotnet-version":      "Get .NET version",
	"get-go-version":          "Get Go version",
	"get-node-version":        "Get Node version",
	"get-python-version":      "Get Python version",
	"get-java-version":        "Get Java version",
	"git-status":              "Git status - git-status [path]",
	"git-log":                 "Git log - git-log [path]",
	"git-diff":                "Git diff",
	"shutdown-restart":        "Shutdown/restart - shutdown-restart <shutdown|restart|logoff|sleep|hibernate>",
	"create-restore-point":    "Create restore point",
	"get-pending-reboot":      "Get pending reboot status",
	"generate-password":       "Generate password",
	"generate-uuid":           "Generate UUID",
	"encode-base64":           "Encode base64 - encode-base64 <text>",
	"decode-base64":           "Decode base64",
	"hash-text":               "Hash text - hash-text <text>",
	"ping":                    "Ping",
	"screenshot-now":          "Take screenshot",
}
